//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftExcelCopier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class vi_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftExcelCopier.vi-VN", typeof(vi_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        internal static string buttonCancelText {
            get {
                return ResourceManager.GetString("buttonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        internal static string buttonNoText {
            get {
                return ResourceManager.GetString("buttonNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string buttonOKText {
            get {
                return ResourceManager.GetString("buttonOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        internal static string buttonYesText {
            get {
                return ResourceManager.GetString("buttonYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo tập tin cho tháng mới..
        /// </summary>
        internal static string cannotCreateFile {
            get {
                return ResourceManager.GetString("cannotCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể mở tập tin {0}. Lưu ý: phải đóng tập tin trước khi chạy chương trình..
        /// </summary>
        internal static string cannotOpenFile {
            get {
                return ResourceManager.GetString("cannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép thành công!.
        /// </summary>
        internal static string copySucessfully {
            get {
                return ResourceManager.GetString("copySucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu ngày {0}. Vui lòng kiểm tra lại!.
        /// </summary>
        internal static string dataNotFound {
            get {
                return ResourceManager.GetString("dataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu ngày {0} tại sheet {1}. Đã thực hiện sao chép tại các sheet còn lại..
        /// </summary>
        internal static string dataNotFoundInSomeSheet {
            get {
                return ResourceManager.GetString("dataNotFoundInSomeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string errorCaption {
            get {
                return ResourceManager.GetString("errorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại. Vui lòng kiểm tra lại!.
        /// </summary>
        internal static string fileNotExist {
            get {
                return ResourceManager.GetString("fileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tập tin cần sao chép bằng nút Chọn tập tin ở trên!.
        /// </summary>
        internal static string filePathEmpty {
            get {
                return ResourceManager.GetString("filePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string guideCaption {
            get {
                return ResourceManager.GetString("guideCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string infoCaption {
            get {
                return ResourceManager.GetString("infoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn không hợp lệ. Vui lòng kiểm tra lại!.
        /// </summary>
        internal static string invalidFilePath {
            get {
                return ResourceManager.GetString("invalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu kết quả sao chép?.
        /// </summary>
        internal static string saveQuestion {
            get {
                return ResourceManager.GetString("saveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công!.
        /// </summary>
        internal static string saveSuccessfully {
            get {
                return ResourceManager.GetString("saveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác thất bại. Vui lòng thực hiện lại!.
        /// </summary>
        internal static string systemError {
            get {
                return ResourceManager.GetString("systemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các ngày sao chép đến phải trong cùng một tháng. Vui lòng chọn lại!.
        /// </summary>
        internal static string toDateInAMonth {
            get {
                return ResourceManager.GetString("toDateInAMonth", resourceCulture);
            }
        }
    }
}
